copyright: 2024
title: Challenges, Skills, and Opportunities
author: Abimereki Muzaale, Vincent Jin, and JHU TRC
logo: https://raw.githubusercontent.com/jhutrc/jhutrc.github.io/main/png/hub_and_spoke.jpg
